[package]
name = "bevy_dog"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.16" }
bytemuck = { version = "1.16", features = [ "derive" ] }

[dependencies.image]
version = "0.24"
default-features = false
features = ["png", "jpeg"]

[dev-dependencies]
bevy_egui = "0.34"
